blank_issues_enabled: false
contact_links:
  - name: Lyrion Community Forum Support
    url: https://forums.slimdevices.com/forum/user-forums/3rd-party-software/1641998-announce-virtual-library-creator
    about: Please ask questions that are not related to bug reports or feature requests here.